name: noctua_obox
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  intl: ^0.17.0
  # Gerenciador de estados
  get: ^4.6.5
  # Remote DataBase Back4app
  parse_server_sdk_flutter: ^3.1.3
  # Local DataBase ObjectBox
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  # Google
  google_fonts: ^3.0.1  
  # upload Files
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.8
  # file_picker: ^5.0.1
  # path_provider
  path_provider: ^2.0.11
  # flutter.dev
  url_launcher: ^6.1.5
  # outros
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/  